### ISSUE TITLE
Sourcemaps not used by Rollbar

### ISSUE THREAD

**Issue by avk** [AlexanderPavlenko/sprockets_uglifier_with_source_maps#6]
Hey @AlexanderPavlenko, thanks for this helpful utility. I'm having a continuous issue with Rollbar not using the default source maps the gem generates. Their support and I haven't been able to get to the bottom of it. This is their latest response:

> We think the issue is your minified_url here is incorrect. Here we see:
> Code Version: 81961bcac73fe97447053d95a86751285a03693d 
> Minified Url: //www.therightmargin.com/assets/public-d565741bd571b06dc302624a5b1daa1ad16b7ae0ac5d80e1e2743b930f92cb4e.js 
> Received: 2017-01-23 02:58 pm 
> 
> The minified url has /assets/public-... If I look in the corresponding .map file here you can see the source path has /assets/source/public-...
>
> /assets/sources/public-f7cd52feeca2e7ef2a3e80aea001c2ad776eaa3e285c6774b87d077ae04cd1d3.js
> You just need to change the minified_url. 

* Here's what's visible in Rollbar:

![screen shot 2017-01-30 at 12 38 32 pm](https://cloud.githubusercontent.com/assets/28668/22440620/2713a67a-e6e9-11e6-8438-9ba83c922ca3.png)

* The [minified file](https://www.therightmargin.com/assets/public-d565741bd571b06dc302624a5b1daa1ad16b7ae0ac5d80e1e2743b930f92cb4e.js)

* It's corresponding [source map](https://www.therightmargin.com/assets/maps/public-4afd15da45258b76f601f91fb6209492c618131deba026ab96f2c57aa6c8db7f.js.map)

* My config only has `config.assets.js_compressor = :uglifier_with_source_maps`

The gem looks to be doing everything as expected, according to [your example](https://github.com/AlexanderPavlenko/sprockets_uglifier_with_source_maps#example). Any thoughts on what could be the issue?

**Comment by AlexanderPavlenko** [comment]
Maybe they expect source map to include source code into `sourcesContent` field instead of referencing it in the `sources` fields.

**Comment by avk** [comment]
Yep, Rollbar confirmed it:

> Aha, yes, that is true. Per [our docs](https://rollbar.com/docs/source-maps/): "You can include the source inside the source map. We'll look for it in sourcesContent as per the source map standard." 

Any thoughts on how to proceed or fix?

**Comment by AlexanderPavlenko** [comment]
https://github.com/AlexanderPavlenko/sprockets_uglifier_with_source_maps/tree/sources_content

You can try this version with `config.assets.sourcemaps_embed_source = true`.

**Comment by avk** [comment]
@AlexanderPavlenko thanks. I'm not seeing `sourcesContent` at the top of the map:

```sh
$ head -c115 public/assets/maps/application-2056d377c0539f8327c140dbd4baa97ccb98ca3dfc2526ee12f2df9533124519.js.map
{"version":3,"sources":["?"],"names":["window","goog_snippet_vars","w","google_conversion_id","google_conversion_la
```

but I do see the key later in the file. Is that expected?

**Comment by AlexanderPavlenko** [comment]
Yes, it's a hash, so the keys order is generally doesn't matter.

**Comment by avk** [comment]
@AlexanderPavlenko thanks, I have this working locally but doesn't seem to take in production yet. Is there anything else I may have to do besides `config.assets.sourcemaps_embed_source = true` in my production config?

**Comment by avk** [comment]
@AlexanderPavlenko this works! Would love to see this in a future release 👍

**Comment by AlexanderPavlenko** [comment]
Version 2.1.0 released.

**Comment by coryvirok** [comment]
@AlexanderPavlenko in the output @avk provided I see `"sources":["?"]`. I've been investigating and it appears that other UglifyJs2 users have seen this but I'm not sure I understand what the workaround is. Do you know how to get the sources list to contain the actual source filenames?

Thanks!

**Comment by coryvirok** [comment]
@AlexanderPavlenko any suggestions?

**Comment by AlexanderPavlenko** [comment]
@coryvirok assuming `sources` field is for URLs, original source filenames may be saved as comments inside those sources.

**Comment by coryvirok** [comment]
The `sources` field is supposed to contain the ordered list of input filenames which the source map was generated from. 

E.g. If you minify and generate a source map for files a.js, b.js, c.js you will end up with out.min.js and out.min.map. The `sources` key in the sourcemap should contain `["a.js", "b.js", "c.js"]`

The order is important here since it corresponds with the VLQ offset for which file the symbol is in. If `sources == ["?"]` it essentially breaks sourcemapping. 

More info here: https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/

But it sounds like fixing the `sources` key is out of scope for this library. Is that correct?
